events {
    worker_connections 1024;
}

http {
    upstream nextjs_app {
        server web:3000;
    }
    upstream socket_app {
        server worker:3001;
    }

    server {
        listen 80;

        location /socket.io/ {
            proxy_pass http://socket_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://nextjs_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
